### ISSUE TITLE
Proposal: Log if a header cannot be parsed into a HashWithIndifferentAccess

### ISSUE THREAD

**Issue by NiklasHae** [unpoly/unpoly-rails#8]
Hi,

sending anything that is valid JSON but will not result in a Hash (e.g. `"1"`, `"test"`, `[]`) in at least the `X-Up-Context` and `X-Up-Fail-Context` headers leads to exceptions. These exceptions are mostly generated by security-scanners, similar to #3.

Since for the resolution of #3 we decided to log instead of raising out, I'd suggest to handle such a case similiarly. This would reduce the noise generated by such scanners.

Example:

```
get "/some-unpoly-rails-route", headers: { "X-Up-Fail-Context" => '"somesnippet"' }
get "/some-unpoly-rails-route", headers: { "X-Up-Fail-Context" => '42' }
```

Backtrace:

```
Unpoly::Rails::Error:
       Constructor args must be an ActiveSupport::HashWithIndifferentaccess
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change/context.rb:73:in `ensure_indifferent_access'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change/context.rb:12:in `initialize'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change.rb:192:in `new'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change.rb:192:in `context'
     # (eval):16:in `context'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change.rb:200:in `context_changes'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change.rb:260:in `block in after_action'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change/field_definition.rb:28:in `no_vary'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/change.rb:254:in `after_action'
     # .rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/unpoly-rails-3.7.2/lib/unpoly/rails/controller.rb:12:in `block in prepended'
```

**Comment by triskweline** [comment]
Released as 3.7.3.1.
